// Standard libs
#include <iostream>
#include <iomanip>
#include <vector>
// Bioinformatics libs
#include <fundamentals.hpp>
#include <genetics.hpp>
#include <analysis.hpp>
#include <biomath.hpp>

int main() {
    std::cout << std::fixed << std::setprecision(3);

    bioinfo::AAString a = bioinfo::AAString(
        std::string("header"),
        std::string("MMYDNQHDIKIKFERVPECSNMFSAWMDWNFLMCTWDFHVIRTLENFDRVWHYSTWSIAIIAANYYEVQIHTWNTTGICQGVVKIHKAYIFGNQKSVKWDDWNMAHQHMCNMHASQGMEGGKHWPFMHNSIIWLNFEHWFWPNFWKIEQGCMWICDECDQYTPKVMEGNCYQYAEDSSTGYPSDQTLAHIKCSNQVYNYSGFLMASKHWICILVNTECWRRVFNSCNLSGMEARWGMDMKHFTYYQHSCRSHDNPVQDIALFGPRDDTKTQESGANSHQDRSEMFRWWHQKQWFILLREKHTAWWNDEFIMGNFMASIEGTRDQWGRHCARKGCWWDFPKTEGHRISANCLMREWAVYVMRQHYGKSCHCATLCYPGFPYGPNCTTGMNNHDDSGFEMAQILVEKHKYALLYPPGRMQHHIEHYHVKHPWVRVFERHLVRYWFQVPVDRAVNWCRIKGEEAHLQPKHVRNIDKDNIKVQRQDRCCPTGCDERKPQMVCHIRDQKFIIQRMQKGPRSNKPWTPWDGNLGSLFPWKPKSDEDQGGSCIDKCHAFICFMQDNPAHTYHMEPYQPNMQFRIVWNIVTGYKMHTMGEPHYIDEVHRCYGYDNGRSHIMCFNTRCQGLDQTNWKLDTLNQNIAFDLSRMGHWFPWICLELGEEDKVDKGMCTSDLAPFIHTPMGKIIIVAVPMCPMAGPMSLRMFKEIVSMYSIADHKFSDVRLYGYCINTYKPNMNYTFPTPQQTMNKWNWSPLCPSVEASPTNSPDDDAVIRAIILQTDEIPIDNRGYPEMQEEQDTTGTSMCSKIFALPPQQNMCVDFFMMTWNFDSTFSYLGLNSCGETLRANYLLEPSLVWLLRKHSCLAEEWSGCNHNAGYEHQMSTCAAGYLEFYRNHFGFVEWGHPRQWLYMYLTKLLMTMEYWWWKAARLPCHGYPSCNNCYMHVFWQMNTKHWHKYEIDLHWSPLHCPTVLCQHHQSKMPATITRTSRGSRETNCISGSTCHK*"),
        bioinfo::GeneticCode::STANDARD_GENETIC_CODE
    );

    std::cout << inferredRNACount(a, bioinfo::GeneticCodeTranscribableUnits::STANDARD_GENETIC_CODE, 1000000) << std::endl;

    return 0;
}